import { test, expect } from '@playwright/test'

test('double-clicking a wrapped PDF sentence highlights its precise formatted TeX sentence', async ({ page }) => {
  await page.goto('/?sentences')
  const span = page.locator('.textLayer span').filter({ hasText: 'method works. Last sentence.' })
  await expect(span).toBeVisible()
  await span.dblclick({ position: { x: 20, y: 8 } })
  await expect(page.getByTestId('source-highlight')).toHaveText(/The efficient\s+method works\./)
  await expect(page.locator('.editor-preview-selection')).toBeVisible()
  await expect(page.getByTestId('source-range')).toHaveText(JSON.stringify({ start: { line: 2, column: 17 }, end: { line: 2, column: 53 } }))
})

test('double-clicking TeX highlights the matching PDF sentence across lines', async ({ page }) => {
  await page.goto('/?sentences')
  await expect(page.locator('.textLayer span').filter({ hasText: 'method works.' })).toBeVisible()
  const source = page.getByTestId('source-editor').locator('.view-line').filter({ hasText: 'First sentence.' })
  await expect(source).toBeVisible()
  const point = await source.evaluate((line) => {
    const walker = document.createTreeWalker(line, NodeFilter.SHOW_TEXT)
    while (walker.nextNode()) {
      const node = walker.currentNode
      const index = node.textContent.indexOf('efficient')
      if (index < 0) continue
      const range = document.createRange()
      range.setStart(node, index)
      range.setEnd(node, index + 9)
      const rect = range.getBoundingClientRect()
      return { x: rect.x + rect.width / 2, y: rect.y + rect.height / 2 }
    }
    throw new Error('Source word not rendered')
  })
  await page.mouse.dblclick(point.x, point.y)
  await expect(page.locator('.pdf-sentence-highlight')).toHaveCount(2)
  await expect(page.getByTestId('source-highlight')).toHaveText('The \\textbf{efficient} method works.')
})

test('edits a PDF sentence manually, recompiles its preview, and undoes the change', async ({ page }) => {
  await page.goto('/?sentences')
  const span = page.locator('.textLayer span').filter({ hasText: 'method works. Last sentence.' })
  await span.dblclick({ position: { x: 20, y: 8 } })
  const dialog = page.getByRole('dialog', { name: 'Edit PDF sentence' })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Edit manually' }).click()
  const field = dialog.getByRole('textbox', { name: 'Sentence', exact: true })
  await expect(field).toHaveValue('The \\textbf{efficient} method works.')
  await field.fill('The method is effective.')
  await dialog.getByRole('button', { name: 'Apply and refresh PDF' }).click()
  await expect(dialog.getByText('PDF refreshed.', { exact: true })).toBeVisible()
  await expect(page.locator('.textLayer span').filter({ hasText: 'The method is effective.' })).toBeVisible()
  await expect(page.getByTestId('source-editor')).toContainText('First sentence. The method is effective. Last sentence.')
  await dialog.getByRole('button', { name: 'Undo this edit' }).click()
  await expect(dialog.getByText('The sentence edit was undone and the PDF refreshed.')).toBeVisible()
  await expect(page.locator('.textLayer span').filter({ hasText: 'The efficient method works.' })).toBeVisible()
})

test('reviews an AI-polished sentence before applying it from the PDF', async ({ page }) => {
  await page.goto('/?sentences')
  await page.locator('.textLayer span').filter({ hasText: 'method works. Last sentence.' }).dblclick({ position: { x: 20, y: 8 } })
  const dialog = page.getByRole('dialog', { name: 'Edit PDF sentence' })
  await dialog.getByRole('button', { name: 'Polish with AI' }).click()
  await expect(dialog.getByRole('textbox')).toHaveValue('The method is effective.')
  await expect(page.getByTestId('source-editor')).toContainText('The \\textbf{efficient} method works.')
  await dialog.getByRole('button', { name: 'Apply and refresh PDF' }).click()
  await expect(page.locator('.textLayer span').filter({ hasText: 'The method is effective.' })).toBeVisible()
})

test('edits and undoes sentences with the source editor hidden in the PDF workspace', async ({ page }) => {
  await page.goto('/?sentences&workspace')
  const source = page.getByTestId('source-editor')
  await expect(source).toBeVisible()
  await page.getByRole('button', { name: 'PDF workspace', exact: true }).click()
  await expect(source).toBeHidden()
  const workspace = await page.locator('main').boundingBox()
  const preview = await page.locator('.preview-pane').boundingBox()
  expect(preview.width).toBeGreaterThan(workspace.width * 0.95)
  await page.locator('.textLayer span').filter({ hasText: 'method works. Last sentence.' }).dblclick({ position: { x: 20, y: 8 } })
  const dialog = page.getByRole('dialog', { name: 'Edit PDF sentence' })
  await dialog.getByRole('button', { name: 'Edit manually' }).click()
  await dialog.getByRole('textbox').fill('The method is effective.')
  await dialog.getByRole('button', { name: 'Apply and refresh PDF' }).click()
  await expect(page.locator('.textLayer span').filter({ hasText: 'The method is effective.' })).toBeVisible()
  await expect(source).toBeHidden()
  await dialog.getByRole('button', { name: 'Undo this edit' }).click()
  await expect(page.locator('.textLayer span').filter({ hasText: 'The efficient method works.' })).toBeVisible()
  await dialog.getByRole('button', { name: 'Close sentence editor' }).click()
  await page.getByRole('button', { name: 'Show TeX and PDF' }).click()
  await expect(source).toBeVisible()
  await expect(source).toContainText('The \\textbf{efficient} method works.')
})

test('edits the retained TeX source in a drawer and refreshes the full-width PDF', async ({ page }) => {
  await page.goto('/?sentences&workspace')
  await expect(page.locator('.textLayer span').filter({ hasText: 'method works. Last sentence.' })).toBeVisible()
  await page.getByRole('button', { name: 'PDF workspace', exact: true }).click()
  await page.getByRole('button', { name: 'Edit source', exact: true }).click()
  const source = page.getByTestId('source-editor')
  await expect(source).toBeVisible()
  await source.locator('.view-lines').click()
  const macKeys = await page.evaluate(() => /Macintosh|Mac OS X/.test(navigator.userAgent))
  await page.keyboard.press(macKeys ? 'Meta+a' : 'Control+a')
  await page.keyboard.type('\\begin{document}\nFirst sentence. The revised method works. Last sentence.\n\\end{document}')
  await expect(source).toContainText('The revised method works.')
  await page.getByRole('button', { name: 'Save and refresh PDF' }).click()
  await expect.poll(() => page.evaluate(() => sessionStorage.getItem('compiled-source'))).toBe('\\begin{document}\nFirst sentence. The revised method works. Last sentence.\n\\end{document}')
  await page.getByRole('button', { name: 'Back to PDF', exact: true }).click()
  await expect(source).toBeHidden()
  await expect(page.locator('.textLayer span').filter({ hasText: 'The revised method works.' })).toBeVisible()
})

test('keeps editing controls reachable in the compact PDF workspace', async ({ page }) => {
  await page.setViewportSize({ width: 800, height: 600 })
  await page.goto('/?sentences&workspace')
  await expect(page.locator('.textLayer span').first()).toBeVisible()
  await page.getByRole('button', { name: 'PDF workspace', exact: true }).click()
  const sourceToggle = page.getByRole('toolbar', { name: 'PDF', exact: true }).getByRole('button', { name: 'Edit source' })
  await expect(sourceToggle).toBeVisible()
  await expect(page.getByText(/Double-click a sentence to edit/)).toBeVisible()
  await sourceToggle.click()
  const sourcePanel = page.locator('#workspace-source-editor')
  await expect(sourcePanel.getByText('main.tex', { exact: true })).toBeVisible()
  await expect(sourcePanel.getByRole('button', { name: 'Save and refresh PDF' })).toBeInViewport()
  const bounds = await sourcePanel.boundingBox()
  expect(bounds.width).toBeLessThan(600)
  expect(bounds.y + bounds.height).toBeLessThanOrEqual(600)
  await page.keyboard.press('Escape')
  await expect(sourcePanel).toBeHidden()
  await expect(sourceToggle).toBeFocused()
  await page.locator('.textLayer span').filter({ hasText: 'method works. Last sentence.' }).dblclick({ position: { x: 20, y: 8 } })
  const dialog = page.getByRole('dialog', { name: 'Edit PDF sentence' })
  await expect(dialog.getByText('Original PDF text')).toBeVisible()
  await dialog.getByRole('button', { name: 'Edit manually' }).click()
  const field = dialog.getByRole('textbox')
  await field.fill('Temporary draft.')
  await dialog.getByRole('button', { name: 'Reset draft' }).click()
  await expect(field).toHaveValue('The \\textbf{efficient} method works.')
  await field.fill('The method is effective.')
  await field.press('Control+Enter')
  await expect(dialog.getByText('Applied sentence', { exact: true })).toBeVisible()
  await expect(dialog.getByText('The method is effective.', { exact: true })).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Done', exact: true })).toBeFocused()
  await dialog.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.locator('.preview-container')).toBeFocused()
})
