/**
 * Renderer-side names for the Rust commands available during the incremental
 * Tauri migration. Keep this map aligned with `src-tauri/build.rs` and the
 * handler list in `src-tauri/src/lib.rs`.
 */
export const TAURI_COMMANDS = {
  openFile: 'open_file',
  openDirectory: 'open_directory',
  activateProject: 'activate_project',
  readDirectory: 'read_directory',
  readFile: 'read_file',
  saveFile: 'save_file',
  saveFileAs: 'save_file_as',
  saveFileBatch: 'save_file_batch',
  createFile: 'create_file',
  createDirectory: 'create_directory',
  copyFile: 'copy_file',
  renamePath: 'rename_path',
  deletePath: 'delete_path',
  readFileBase64: 'read_file_base64',
  readFileBinary: 'read_file_binary',
  gitIsRepo: 'git_is_repo',
  gitInit: 'git_init',
  gitStatus: 'git_status',
  gitStage: 'git_stage',
  gitUnstage: 'git_unstage',
  gitCommit: 'git_commit',
  gitDiff: 'git_diff',
  gitLog: 'git_log',
  gitFileLog: 'git_file_log',
  loadPackageData: 'load_package_data',
  getProjectIndex: 'get_project_index',
  parseBibFile: 'parse_bib_file',
  findBibInProject: 'find_bib_in_project',
  scanLabels: 'scan_labels',
  zoteroProbe: 'zotero_probe',
  zoteroSearch: 'zotero_search',
  zoteroCiteCayw: 'zotero_cite_cayw',
  zoteroExportBibtex: 'zotero_export_bibtex',
  zoteroSyncCollection: 'zotero_sync_collection',
  watchDirectory: 'watch_directory',
  unwatchDirectory: 'unwatch_directory',
  loadSettings: 'load_settings',
  saveSettings: 'save_settings',
  addRecentProject: 'add_recent_project',
  removeRecentProject: 'remove_recent_project',
  updateRecentProject: 'update_recent_project',
  compile: 'compile_latex',
  cancelCompile: 'cancel_compile',
  synctexForward: 'synctex_forward',
  synctexInverse: 'synctex_inverse',
  synctexBuildLineMap: 'synctex_build_line_map',
  checkAppUpdate: 'check_app_update',
  downloadAndInstallUpdate: 'download_and_install_update',
  restartApp: 'restart_app'
} as const
